### ISSUE TITLE
2016 Roadmap

### ISSUE THREAD

**Issue by mccxiv** [mccxiv/tc#279]
Hello friends. Progress is slower now that I have a job (yay). The good news is that I myself am an active user of this app, which means if something is broken I have a selfish interest in fixing it.

Now that I can only work on Tc a few hours a week, it's best to plan out and prioritize features.  
So here's the list I want to work on:
- [x] 1. [#273] Add tiger/zebra striping to chat.
- [x] 2. [#278] Add better support for emojis. Use our own images instead of relying on the OS.
- [ ] 3. [#8] Add an emote menu. Click it to see all emotes you can use and add them to chat.
- [ ] 4. [#277] Show a user's chat history.

**Comment by mccxiv** [comment]
We got #278 almost for free thanks to a Chromium update.

Now I need to work on the emote menu

**Comment by mccxiv** [comment]
Getting there I guess. 

New top priority is: reordering tabs
